name: Saludo

on:
  push:
    branches:
      - main
      - develop

env:
  Mi_Nombre: "Fabián Cubas"

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo desde main
        if: github.ref == 'refs/heads/main'
        run: echo "Hola desde main, soy $Mi_Nombre"

      - name: Saludo desde develop
        if: github.ref == 'refs/heads/develop'
        run: echo "Hola desde develop, soy $Mi_Nombre"
